@base = http://localhost:3000
@postId = {{postId}}
@commentId = {{commentId}}

###
# Create post
POST {{base}}/post
Content-Type: application/json

{
  "message": "My first post body",
  "sender": "123456789"
}

###
# Get all posts
GET {{base}}/post

###
# Get posts by sender
GET {{base}}/post?sender=123456789

###
# Get post by id
GET {{base}}/post/{{postId}}

###
# Replace post content
PUT {{base}}/post/{{postId}}
Content-Type: application/json

{
  "message": "Updated message",
  "sender": "123456789"
}

###
# Create comment
POST {{base}}/comment
Content-Type: application/json

{
  "post": "{{postId}}",
  "text": "Nice post!",
  "author": "987654321"
}

###
# Get all comments
GET {{base}}/comment

###
# Get comments for a post
GET {{base}}/comment?post={{postId}}

###
# Update comment
PUT {{base}}/comment/{{commentId}}
Content-Type: application/json

{
  "post": "{{postId}}",
  "text": "Edited comment text",
  "author": "987654321"
}

###
# Delete comment
DELETE {{base}}/comment/{{commentId}}

###
# User register
POST {{base}}/auth/register
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "123456789"
}

###
# User login
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "987654321"
}

//todo: the user controller